import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Next website template</title>
				<meta
					name="meta description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<h1>Next Website Template</h1>
			</div>
		</div>
	);
}
